<?php if ($form->hasErrors()): ?>
    <?php foreach ($form->getErrors() as $error): ?>
        <div class="form-error">
            <i class="fa fa-times"></i> <?= $error ?>
        </div>
    <?php endforeach ?>
<?php endif ?>
<?php foreach ($form->getInputs() as $input): ?>
    <div class="form-row">
        <div class="form-label">
            <label for="<?= $form->getId($input->getName()) ?>"><?= $form->getLabel($input->getName()) ?></label>
        </div>
        <div class="form-input">
            <?php if ($input->hasError()): ?>
                <div class="form-error">
                    <i class="fa fa-times"></i> <?= $input->getError() ?>
                </div>
            <?php endif ?>
            <?= $input->fetch() ?>
        </div>
    </div>
<?php endforeach ?>
