<h1><?= $title ?></h1>
<?php $this->fetch(':admin/listButtons') ?>
<?php if ($filterForm): ?>
    <div class="filter-form">
        <?= $this->fetch(':admin/filterForm') ?>
    </div>
<?php endif ?>
<div class="clear"></div>
<?php if ($records): ?>
    <?= $this->fetch(':admin/list') ?>
<?php else: ?>
    <div class="no-results"><?= $translation->get('admin', 'no_results'); ?></div>
<?php endif ?>
