<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php foreach ($view->getStyles() as $style): ?>
        <link rel="stylesheet" type="text/css" href="<?= $style ?>">
    <?php endforeach ?>
</head>
<body class="wrapper">
    <header>
        Admin
        <!--
        <div>
            <input type="text">
            <button type="submit" class="fa-button">
                <i class="fa fa-search"></i>
            </button>
            
        </div>
        -->
    </header>
    <nav>
        <ul>
            <?php foreach ($view->get('adminMenu')->getItems() as $item): ?>
                <li><a href="<?= $router->getUrl($item->getRoute()) ?>"><span><i class="fa fa-<?= $item->getIcon() ?>"></i></span><?= $item->getTitle() ?></a></li>
            <?php endforeach ?>
        </ul>
    </nav>

    <main>
        <?= $content ?>
    </main>

    <?php foreach ($view->getScripts() as $script): ?>
        <script type="text/javascript" src="<?= $script ?>"></script>
    <?php endforeach ?>

    <!-- Memory usage: <?= memory_get_usage() / 1024 ?>K -->

</body>
</html>