<!DOCTYPE html>
<html>
<head>
    <base href="<?= $router->getBaseUrl() ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php foreach ($view->getStyles() as $style): ?>
        <link rel="stylesheet" type="text/css" href="<?= $style['source'] ?>" media="<?= $style['media'] ?>">
    <?php endforeach ?>
</head>
<body class="wrapper">
    <header>
        Admin
    </header>
    <nav>
        <ul>
            <?php foreach ($view->get('adminMenu')->getItems() as $item): ?>
                <li><a href="<?= $router->getUrl($item->getRoute()) ?>"><span><i class="fa fa-<?= $item->getIcon() ?>"></i></span><?= $item->getTitle() ?></a></li>
            <?php endforeach ?>
        </ul>
    </nav>

    <main>
        <?= $content ?>
    </main>

    <?= $view->fetch(':core/scripts') ?>

    <!-- Memory usage: <?= memory_get_usage() / 1024 ?>K -->

</body>
</html>