<?php if ($pageNumber == 0): ?>
    <i class="fa fa-angle-double-left"></i>
    <i class="fa fa-angle-left"></i>
<?php else: ?>
    <a href="<?= $router->getUrl('admin', ['page' => 0]) ?>"><i class="fa fa-angle-double-left"></i></a>
    <a href="<?= $router->getUrl('admin', ['page' => $pageNumber - 1]) ?>"><i class="fa fa-angle-left"></i></a>
<?php endif ?>

<?php for ($i = 0; $i < $maxPageNumber; $i++): ?>
    <?php if ($i == $pageNumber): ?>
        <?= $i + 1 ?>
    <?php else: ?>
        <a href="<?= $router->getUrl('admin', ['page' => $i]) ?>"><?= $i + 1 ?></a>
    <?php endif ?>
<?php endfor ?>

<?php if ($pageNumber == $maxPageNumber - 1): ?>
    <i class="fa fa-angle-right"></i>
    <i class="fa fa-angle-double-right"></i>
<?php else: ?>
    <a href="<?= $router->getUrl('admin', ['page' => $pageNumber + 1]) ?>"><i class="fa fa-angle-right"></i></a>
    <a href="<?= $router->getUrl('admin', ['page' => $maxPageNumber - 1]) ?>"><i class="fa fa-angle-double-right"></i></a>
<?php endif ?>