<?php if ($pager->hasPrev()): ?>
    <a href="<?= $pager->getFirstUrl() ?>"><i class="fa fa-angle-double-left"></i></a>
    <a href="<?= $pager->getPrevUrl() ?>"><i class="fa fa-angle-left"></i></a>
<?php else: ?>
    <i class="fa fa-angle-double-left"></i>
    <i class="fa fa-angle-left"></i>
<?php endif ?>

<?php for ($i = 0; $i < $pager->getMaxPage(); $i++): ?>
    <?php if ($i == $pager->getPage()): ?>
        <?= $i + 1 ?>
    <?php else: ?>
        <a href="<?= $pager->getUrl($i) ?>"><?= $i + 1 ?></a>
    <?php endif ?>
<?php endfor ?>

<?php if ($pager->hasNext()): ?>
    <a href="<?= $pager->getNextUrl() ?>"><i class="fa fa-angle-right"></i></a>
    <a href="<?= $pager->getLastUrl() ?>"><i class="fa fa-angle-double-right"></i></a>
<?php else: ?>
    <i class="fa fa-angle-right"></i>
    <i class="fa fa-angle-double-right"></i>
<?php endif ?>