<?php if ($page == 0): ?>
    <i class="fa fa-angle-double-left"></i>
    <i class="fa fa-angle-left"></i>
<?php else: ?>
    <a href="<?= $router->getUrl('admin&page=0') ?>"><i class="fa fa-angle-double-left"></i></a>
    <a href="<?= $router->getUrl('admin&page='.($page - 1)) ?>"><i class="fa fa-angle-left"></i></a>
<?php endif ?>

<?php for ($i = 0; $i < $maxPage; $i++): ?>
    <?php if ($i == $page): ?>
        <?= $i + 1 ?>
    <?php else: ?>
        <a href="<?= $router->getUrl('admin&page='.$i) ?>"><?= $i + 1 ?></a>
    <?php endif ?>
<?php endfor ?>

<?php if ($page == $maxPage - 1): ?>
    <i class="fa fa-angle-right"></i>
    <i class="fa fa-angle-double-right"></i>
<?php else: ?>
    <a href="<?= $router->getUrl('admin&page='.($page + 1)) ?>"><i class="fa fa-angle-right"></i></a>
    <a href="<?= $router->getUrl('admin&page='.($maxPage - 1)) ?>"><i class="fa fa-angle-double-right"></i></a>
<?php endif ?>