<table>
    <thead>
    <tr>
        <th><?= $translation->get('message', 'subject') ?></th>
        <th><?= $translation->get('message', 'title') ?></th>
        <th><?= $translation->get('message', 'time') ?></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($messages as $message): ?>
            <tr<?php if (!$message->get('read')): ?> class="unread"<?php endif ?>>
                <td><a href="<?= $router->getUrl('message/view/'.$message->get('id')) ?>"><?= $message->get('subject') ?></a></td>
                <td><a href="<?= $router->getUrl('message/view/'.$message->get('id')) ?>"><?= $this->escape($message->get('text')) ?></a></td>
                <td><?= $messageService->formatTimestamp($message->get('created_on')) ?></td>
                <td><a href="javascript:Confirm.redirect('delete', '<?= $router->getUrl('message/delete/'.$message->get('id')) ?>')"><?= $translation->get('message', 'delete') ?></a></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
