<h1><?= $translation->get('message', 'my_messages') ?></h1>
<?= $this->fetch(':message/menu', ['active' => $sent ? 'sent' : 'inbox']) ?>
<h2><?= $subtitle ?></h2>
<?php if ($user->hasFlash('message_sent')): ?>
    <div class="info-box">
        <?= $user->getFlash('message_sent') ?>
    </div>
<?php endif; ?>
<div class="message-list">
    <?php if ($messages): ?>
        <?= $this->fetch(':core/pager') ?>
        <?= $this->fetch(':message/listTable') ?>
        <?= $this->fetch(':core/pager') ?>
    <?php else: ?>
        <p><?= $translation->get('message', 'no_results') ?></p>
    <?php endif; ?>
</div>
