<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="vendor/fontawesome/web-fonts-with-css/css/fontawesome-all.min.css" media="all">
    <link rel="stylesheet" type="text/css" href="components/admin/static/reset.css" media="all">
    <link rel="stylesheet" type="text/css" href="components/admin/mediaBrowser/static/browser.css" media="all">
</head>
<body class="wrapper">
    <header>
        Media
    </header>
    <nav>
        <div>
            <div class="buttons">
                <a href="#" title="Add"><i class="fa fa-plus-circle"></i></a>
                <a href="#" title="Rename"><i class="fa fa-pencil-alt"></i></a>
                <a href="#" title="Delete"><i class="fa fa-trash"></i></a>
                <div class="clear"></div>        
            </div>
            <div id="folders"></div>
        </div>
    </nav>
    <main>
        <a href="javascript:window.opener.CKEDITOR.tools.callFunction(<?= $request->get('CKEditorFuncNum') ?>, 'http://dynart.net/images/logo2.png')" class="insert"><i class="fa fa-check-circle"></i>Use the selected</a>
        <div class="path">
            <a href="#">Home</a> /
            <a href="#">Folder 1</a> /
            Folder 3
        </div>
        <div class="buttons">
            <a href="#" class="disabled" title="Delete"><i class="fa fa-trash"></i></a>
            <a href="#" class="disabled" title="Rename"><i class="fa fa-pencil-alt"></i></a>
            <a href="#" style="width:auto;"><i class="fa fa-upload"></i> Upload</a>
            <div class="clear"></div>        
        </div>
        <div id="files" class="items"></div>
    </main>
    
    <script type="text/javascript" src="components/admin/mediaBrowser/static/browser.js"></script>
    <script type="text/javascript">
        MediaBrowser.init({
            foldersRequestUrl: '<?= $router->getUrl('mediabrowser/folders') ?>',
            filesRequestUrl: '<?= $router->getUrl('mediabrowser/files') ?>',
            thumbnailRequestUrl: '<?= $router->getUrl('mediabrowser/thumbnail') ?>'
        });
        MediaBrowser.addFolder(<?= json_encode($folder) ?>);
        MediaBrowser.clickFolder(<?= $folder['id'] ?>);
    </script>
    
    
</body>
</html>
