<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="<?= $router->getBaseUrl() ?>vendor/fontawesome/web-fonts-with-css/css/fontawesome-all.min.css" media="all">
    <link rel="stylesheet" type="text/css" href="<?= $router->getBaseUrl() ?>components/admin/static/reset.css" media="all">
    <link rel="stylesheet" type="text/css" href="<?= $router->getBaseUrl() ?>components/admin/mediaBrowser/static/mediaBrowser.css" media="all">
</head>
<body class="wrapper">
    <div id="upload_progress">
        <div><span></span></div>
    </div>
    <header>
        Media
    </header>
    <nav>
        <div>
            <div class="buttons buttons-folder">
                <a id="folder_add_button" class="disabled" title="Add"><i class="fa fa-plus-circle"></i></a>
                <a id="folder_rename_button" class="disabled" title="Rename"><i class="fa fa-pencil-alt"></i></a>
                <a id="folder_delete_button" class="disabled" title="Delete"><i class="fa fa-trash"></i></a>
                <div class="clear"></div>
            </div>
            <div id="folders"></div>
        </div>
    </nav>
    <main>
        <a id="file_use_button"><i class="fa fa-check-circle"></i>Use selected</a>
        <div class="buttons buttons-file">
            <input type="file" id="upload_file"> 
            <a id="file_delete_button" class="disabled" title="Delete"><i class="fa fa-trash"></i></a>
            <a id="file_rename_button" class="disabled" title="Rename"><i class="fa fa-pencil-alt"></i></a>
            <a id="file_upload_button" class="disabled" style="width:auto;"><i class="fa fa-upload"></i> Upload</a>
            <div class="clear"></div>        
        </div>
        <div id="breadcrumb" class="path"></div>
        <div id="files" class="items"></div>
    </main>
    
    <script type="text/javascript" src="<?= $router->getBaseUrl() ?>components/admin/mediaBrowser/static/mediaBrowser.js?<?= filemtime('components/admin/mediaBrowser/static/mediaBrowser.js') ?>"></script>
    <script type="text/javascript">
        MediaBrowser.init({
            locale: '<?= $request->get('locale') ?>',
            foldersUrl: '<?= $router->getUrl('mediabrowser/folders') ?>',
            filesUrl: '<?= $router->getUrl('mediabrowser/files') ?>',
            thumbnailUrl: '<?= $router->getUrl('media/thumbnail/{id}', ['width' => $thumbnailSize, 'height' => $thumbnailSize]) ?>',
            newFolderUrl: '<?= $router->getUrl('mediabrowser/newfolder') ?>',
            renameUrl: '<?= $router->getUrl('mediabrowser/rename') ?>',
            deleteUrl: '<?= $router->getUrl('mediabrowser/delete') ?>',
            uploadUrl: '<?= $router->getUrl('mediabrowser/upload') ?>',
            mediaUrl: '<?= $router->getUrl('media/get') ?>',
            ckEditorFuncNum: '<?= $request->get('CKEditorFuncNum') ?>',
            inputId: '<?= $request->get('input_id') ?>',
            maximumFileSize: <?= $maximumFileSize ?>
        });
        MediaBrowser.pushFolder(<?= json_encode($folder) ?>);
        MediaBrowser.clickFolder(<?= $folder['id'] ?>);
    </script>
    
    
</body>
</html>
