<?php if ($form->hasErrors()): ?>
	<?php foreach ($form->getErrors() as $error): ?>
		<div class="form-error">
			<?= $error ?>
		</div>
	<?php endforeach ?>
<?php endif ?>
<?php foreach ($form->getInputs() as $input): ?>
	<div class="form-row">
		<label><?= $form->getLabel($input->getName()) ?></label>
		<?= $input->fetch() ?>
		<?php if ($input->hasError()): ?>
			<div class="form-error">
				<?= $input->getError() ?>
			</div>
		<?php endif ?>
	</div>
<?php endforeach ?>

