<!DOCTYPE html>
<html>
<head>
    <base href="<?= $router->getBaseUrl() ?>">
    <?php foreach ($view->getStyles() as $style): ?>
        <link rel="stylesheet" type="text/css" href="<?= $style['source'] ?>" media="<?= $style['media'] ?>">
    <?php endforeach ?>
</head>
<body>

    <nav>
        <a href="<?= $router->getUrl('') ?>"><?= $translation->get('welcome', 'home') ?></a> |
        <?php if ($user->isLoggedIn()): ?>
            <a href="<?= $router->getUrl('logout') ?>"><?= $translation->get('user', 'logout') ?></a> |
            <a href="<?= $router->getUrl('profile/view/'.$user->get('id')) ?>"><?= $translation->get('user', 'profile') ?></a>
        <?php else: ?>
            <a href="<?= $router->getUrl('login') ?>"><?= $translation->get('user', 'login') ?></a> |
            <a href="<?= $router->getUrl('register') ?>"><?= $translation->get('user', 'registration') ?></a>
        <?php endif ?>
    </nav>

    <?= $content ?>

    <?= $view->fetch(':core/scripts') ?>

    <!-- Memory usage: <?= memory_get_usage() / 1024 ?>K -->

</body>
</html>