<div class="pager">
    <?php if ($pager->hasPrev()): ?>
        <span class="first"><a href="<?= $pager->getFirstUrl() ?>">&lt;&lt;</i></a></span>
        <span class="prev"><a href="<?= $pager->getPrevUrl() ?>">&lt;</a></span>
    <?php else: ?>
        <span class="first">&lt;&lt;</span>
        <span class="prev">&lt;</span>
    <?php endif ?>
    <?php for ($i = 0; $i < $pager->getMaxPage(); $i++): ?>
        <?php if ($i == $pager->getPage()): ?>
            <span class="num"><?= $i + 1 ?></span>
        <?php else: ?>
            <span class="num"><a href="<?= $pager->getUrl($i) ?>"><?= $i + 1 ?></a></span>
        <?php endif ?>
    <?php endfor ?>
    <?php if ($pager->hasNext()): ?>
        <span class="next"><a href="<?= $pager->getNextUrl() ?>">&gt;</a></span>
        <span class="last"><a href="<?= $pager->getLastUrl() ?>">&gt;&gt;</a></span>
    <?php else: ?>
        <span class="next">&gt;</span>
        <span class="last">&gt;&gt;</span>
    <?php endif ?>
</div>
