<h1><?= $translation->get('user', 'login') ?></h1>
<form action="<?= $router->getUrl('login', ['ref' => $request->get('ref')]) ?>" method="post">
    <?= $form->fetch() ?>
    <div class="form-row">
        <a href="<?= $router->getUrl('forgot') ?>"><?= $translation->get('user', 'forgotten_password') ?></a>
    </div>
    <div class="form-row">
        <input type="submit" value="<?= $translation->get('user', 'login') ?>">
    </div>
</form>